<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="EPINCHEW0001" failures="1" tests="6" name="Parallel Tests" time="0.089" errors="0" timestamp="2022-08-16T13:10:30 IST">
  <testcase classname="org.hometask.testng.TestNG" name="cos" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [0.8141809705265618] but found [0.5806111842123143]">
      <![CDATA[java.lang.AssertionError: expected [0.8141809705265618] but found [0.5806111842123143]
at org.hometask.testng.TestNG.cos(TestNG.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- cos -->
  <testcase classname="org.hometask.testng.TestNG" name="divNegative" time="0.002"/>
  <testcase classname="org.hometask.testng.TestNG" name="isNegative" time="0.002"/>
  <testcase classname="org.hometask.testng.TestNG" name="isPositive" time="0.001"/>
  <testcase classname="org.hometask.testng.TestNG" name="sqrt" time="0.001"/>
  <testcase classname="org.hometask.testng.TestNG" name="subtract" time="0.002"/>
  <testcase classname="org.hometask.testng.TestNG" name="substraction" time="0.0">
    <ignored/>
  </testcase> <!-- substraction -->
  <testcase classname="org.hometask.testng.TestNG" name="multiplication" time="0.0">
    <ignored/>
  </testcase> <!-- multiplication -->
  <testcase classname="org.hometask.testng.TestNG" name="divison" time="0.0">
    <ignored/>
  </testcase> <!-- divison -->
  <testcase classname="org.hometask.testng.TestNG" name="addition" time="0.0">
    <ignored/>
  </testcase> <!-- addition -->
  <testcase classname="org.hometask.testng.TestNG" name="pow" time="0.0">
    <ignored/>
  </testcase> <!-- pow -->
</testsuite> <!-- Parallel Tests -->
